### ISSUE TITLE
postgres migration error

### ISSUE THREAD

**Issue by ydv-ankit** [vercel/ai-sdk-rag-starter#1]
getting postgresql migration error when running command `pnpm db:migrate`.

![image](https://github.com/user-attachments/assets/585c6be1-977e-4a00-90eb-4dd3470aaa23)

**Comment by nicoalbanese** [comment]
Hi @ydv-ankit - I'm afraid I'm not able reproduce. Are you running postgres locally?

**Comment by ydv-ankit** [comment]
yes, I'm running postgres locally. Do I need containerized one.

**Comment by nicoalbanese** [comment]
Nope - i'm running locally without containerizing. Does your `lib/db/migrate.ts` file have any errors?

Some other ideas:
- try removing node_modules and pnpm-lock file and doing a fresh pnpm run install
- try opening the migration file (ends in .sql) and cutting the first line which is adding the pgvector plugin, running that directly on your postgres instance and then running the migration

**Comment by ydv-ankit** [comment]
cutting the first line which is adding the pgvector plugin worked.
But isn't it required ??

**Comment by nicoalbanese** [comment]
Correct! That's why I was saying make sure you run that line that you cut directly in your postgres instance to ensure it's added. Otherwise the next db:push won't work. Let me know if that works.

**Comment by ydv-ankit** [comment]
thanks man. it worked.

**Comment by nicoalbanese** [comment]
Nice - happy to hear! I'll add it is as a comment on the guide in case others face the same issue.
